### PR TITLE
CI: Migrate from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by DilumAluthge**
Travis has essentially ended their free tier.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@blenessy Would you mind enabling GitHub Actions on this repository?

**Comment by DilumAluthge** [comment]
Bump @blenessy

**Comment by DilumAluthge** [comment]
Bump @blenessy

**Comment by DilumAluthge** [comment]
Bump @blenessy

**Review by blenessy — APPROVED** [review]

**Pull request merged**
